// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingGameExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodinGameExtension.aa1e6aa8-4367-45e0-b7ec-b2f2dd823f68";
        public const string Name = "CodinGameExtension";
        public const string Description = @"
This extension allow to publish code from visual studio to codingame.com";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Renaud R";
        public const string Tags = "";
    }
}
