// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingGameExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CCPackageGuidString = "88419a58-a1cb-4cca-ba77-96c68372bc3e";
        public static Guid CCPackageGuid = new Guid(CCPackageGuidString);

        public const string guidImagesString = "488dd8a2-349c-433f-b061-4298d54a94de";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0010;
        public const int MyCommand = 0x0100;
        public const int ToolbarCG = 0x1005;
        public const int ToolbarCGGroup = 0x1080;
        public const int CommandLoad = 0x0300;
        public const int CommandPush = 0x0301;
        public const int CommandPushNPlay = 0x0302;
        public const int IcoLoad = 0x0001;
        public const int IcoPush = 0x0002;
        public const int IcoPushNPlay = 0x0003;
    }
}